### ISSUE TITLE
ValueError(f'Could not find HHsearch database {database_path}')

### ISSUE THREAD

**Issue by paulgarias** [uvarc/rivanna-docker#3]
I built the singularity file using the Docker file provided. Following the instructions from:

https://staging.rc.virginia.edu/userinfo/rivanna/software/alphafold/#dockerfile

I created the following script with command:

```
export ALPHAFOLD_DATA_PATH=/projects/oarc/staff/acirefs/pgarias/alphafold/scripts/dbs 
export CONTAINERDIR=/scratch/pgarias/alphafold


singularity run -B $ALPHAFOLD_DATA_PATH:/data -B .:/etc --pwd /app/alphafold --nv $CONTAINERDIR/alphafoldnew_latest.sif \
    --fasta_paths=/scratch/pgarias/fastafiles/sarscovid2.fasta \
    --output_dir=/scratch/pgarias/outputdir \
    --model_names=model_1,model_2,model_3,model_4,model_5 \
    --preset=full_dbs \
    --max_template_date=2020-05-14 \
    --data_dir=/data \
    --uniref90_database_path=/data/uniref90/uniref90.fasta \
    --uniclust30_database_path=/data/uniclust30/uniclust30_2018_08/uniclust30_2018_08 \
    --mgnify_database_path=/data/mgnify/mgy_clusters_2018_12.fa \
    --bfd_database_path=/data/bfd/bfd_metaclust_clu_complete_id30_c90_final_seq.sorted_opt  \
    --pdb70_database_path=/data/pdb70 \
    --template_mmcif_dir=/data/pdb_mmcif/mmcif_files/ \
    --obsolete_pdbs_path=/data/pdb_mmcif/obsolete.dat

```

The error that I get is:

```
/opt/alphafoldenv/lib/python3.8/site-packages/absl/flags/_validators.py:203: UserWarning: Flag --preset has a non-None default value; therefore, mark_flag_as_required will pass even if flag is not specified in the command line!
  warnings.warn(
I0819 16:17:39.423708 140346276337472 templates.py:836] Using precomputed obsolete pdbs /data/pdb_mmcif/obsolete.dat.
E0819 16:17:39.427783 140346276337472 hhsearch.py:55] Could not find HHsearch database /data/pdb70
Traceback (most recent call last):
  File "/app/alphafold/run_alphafold.py", line 310, in <module>
    app.run(main)
  File "/opt/alphafoldenv/lib/python3.8/site-packages/absl/app.py", line 312, in run
    _run_main(main, args)
  File "/opt/alphafoldenv/lib/python3.8/site-packages/absl/app.py", line 258, in _run_main
    sys.exit(main(argv))
  File "/app/alphafold/run_alphafold.py", line 245, in main
    data_pipeline = pipeline.DataPipeline(
  File "/app/alphafold/alphafold/data/pipeline.py", line 114, in __init__
    self.hhsearch_pdb70_runner = hhsearch.HHSearch(
  File "/app/alphafold/alphafold/data/tools/hhsearch.py", line 56, in __init__
    raise ValueError(f'Could not find HHsearch database {database_path}')
ValueError: Could not find HHsearch database /data/pdb70
```

I'm wondering if this line here in the instructions is correct:
`--uniclust30_database_path=/data/uniclust30/uniclust30_2018_08/uniclust30_2018_08 \`

All other paths or dir flags point to complete files or directories. 

Thanks for your time!

**Comment by rsdmse** [comment]
The uniclust path is actually correct. The error message indicates pdb70 is wrong. It should be
```
--pdb70_database_path=/data/pdb70/pdb70
```
in the same manner as uniclust.

We have more information about Alphafold on our website [here](https://www.rc.virginia.edu/userinfo/rivanna/software/alphafold/).

**Comment by paulgarias** [comment]
Yes that is correct, I have now resolved the issue and made the change in the 
```
--pdb70_database_path=/data/pdb70/pdb70
```

Thank you!

**Comment by pariskang** [comment]
I installed alphafold_non_docker step by step, but I found the same error as the following:
```
(alphafold) [root@ecs alphafold-2.2.0]# bash run_alphafold.sh -d ./alphafold_data -o ./dummy_test/ -f ./example/query.fasta -t 2020-05-14 -g False
E0704 11:23:00.766234 139973713471296 hhsearch.py:56] Could not find HHsearch database ./alphafold_data//pdb70/pdb70
Traceback (most recent call last):
  File "/root/alphafold-2.2.0/run_alphafold.py", line 422, in <module>
    app.run(main)
  File "/root/miniconda3/envs/alphafold/lib/python3.8/site-packages/absl/app.py", line 312, in run
    _run_main(main, args)
  File "/root/miniconda3/envs/alphafold/lib/python3.8/site-packages/absl/app.py", line 258, in _run_main
    sys.exit(main(argv))
  File "/root/alphafold-2.2.0/run_alphafold.py", line 327, in main
    template_searcher = hhsearch.HHSearch(
  File "/root/alphafold-2.2.0/alphafold/data/tools/hhsearch.py", line 57, in __init__
    raise ValueError(f'Could not find HHsearch database {database_path}')
ValueError: Could not find HHsearch database ./alphafold_data/pdb70/pdb70

```
My pdb70 path in the same as `--pdb70_database_path=/data/pdb70/pdb70`
How to resolve this problem, I sincerely need u help. Thank u~
